import Navbar from "../../components/navbar";
import Head from "next/head";
import { isLightTeme } from "utils/helper";
import { ThemeProvider, useTheme } from "../../lib/themeContext";

export default function Layout({ children }) {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className={`min-h-[100vh] pt-[5rem] ${
          isLightTeme(theme) ? "bg-light" : "bg-dark-600"
        }`}
      >
        {children}
      </div>
    </>
  );
}
